05.26.서영.스테이지2 퍼즐 구현/다이어리/크리쳐등장구현
오류 고칠거
1. Assets\02.Script\06.Puzzles\Stage4_ToyFoodPuzzle.cs(106,14): error CS1061: 'PuzzleDropZone' does not contain a definition for 'IsCorrect' and no accessible extension method 'IsCorrect' accepting a first argument of type 'PuzzleDropZone' could be found (are you missing a using directive or an assembly reference?)

2. Assets\02.Script\06.Puzzles\Stage5_BasementPuzzle.cs(170,13): error CS1061: 'PuzzleDropZone' does not contain a definition for 'IsCorrect' and no accessible extension method 'IsCorrect' accepting a first argument of type 'PuzzleDropZone' could be found (are you missing a using directive or an assembly reference?)

퍼즐드랍존에서 포토렌더러...? 메터리얼 방식에서 이미지 스프라이트 형식으로 바꿔야할듯.. 복잡함.

문 열릴 때, 한번 열린 문 다시 상호작용 시 프롬포트는 문 닫기로 바꾸고 문 다시 원위치로 되돌아가기. 다시 상호작용하면 이미 열린 문은 다시 열리고 원하는대ㅐ로 여닫을 수 있도록 수정.